print("hey just need some information")
myName = input("What is your first name?: ")
print(myName)
myNickname = input("What else do they call you?: ")
print(myNickname)
myBirth = input("When were you born?: ")
print(myBirth)
print("wow that's sooo old!")
print("my bad i got off task..")
myJob = input("What do you do for a living?: ")
print(myJob)
print("oh you make money money")
myStatus = input("so are you married?: ")
print(myStatus)
print("hmm that's that I figued")
